[package]
name = "rig-vertexai"
version = "0.1.0"
edition = "2021"
license = "MIT"
readme = "README.md"
description = "VertexAI model provider Rig integration."
repository = "https://github.com/0xPlaygrounds/rig"

[dependencies]
rig-core = { path = "../rig-core", version = "0" }
google-cloud-aiplatform-v1 = "0.1"
